#!/bin/sh
set -e

lb config noauto \
    --mode debian \
    --system live \
    --distribution bookworm \
    --parent-distribution bookworm \
    --parent-debian-installer-distribution bookworm \
    --archive-areas "main contrib non-free non-free-firmware" \
    --architectures amd64 \
    --binary-images iso-hybrid \
    --bootloaders "grub-efi,syslinux" \
    --bootappend-live "boot=live components consoleblank=0 overlayroot=tmpfs username=kiosk" \
    --bootappend-live-failsafe "boot=live components nomodeset xforcevesa vga=791 overlayroot=tmpfs username=kiosk" \
    --compression gzip \
    --memtest none \
    --iso-application "Lab Kiosk OS" \
    --iso-publisher "School Computer Lab" \
    --iso-volume "LAB_KIOSK" \
    "${@}"
