#!/bin/sh
set -e

lb config noauto \
    --mode debian \
    --system live \
    --distribution bookworm \
    --parent-distribution bookworm \
    --parent-debian-installer-distribution bookworm \
    --archive-areas "main contrib non-free non-free-firmware" \
    --architectures amd64 \
    --binary-images iso-hybrid \
    --bootloaders "grub-efi,syslinux" \
    --bootappend-live "boot=live components quiet splash toram overlayroot=tmpfs vt.global_cursor_default=0 consoleblank=0" \
    --compression zstd \
    --memtest none \
    --iso-application "Lab Kiosk OS" \
    --iso-publisher "School Computer Lab" \
    --iso-volume "LAB_KIOSK" \
    "${@}"
