// Build src/docs_content.generated.ts from the repository's wiki/ folder.
//
// The documentation pages (/docs) are the wiki, rendered by the Worker. A
// Worker cannot read files, so the pages travel in the bundle: this script
// copies each wiki page, and the order of the wiki's sidebar, into one module.
//
//   pnpm run docs           write the module
//   pnpm run docs -- --check   fail when it is out of date (a test does the same)
//
// Edit the wiki, run this, commit both.

import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const wikiDir = join(here, "..", "..", "wiki");
const target = join(here, "..", "src", "docs_content.generated.ts");

/** "Admin-Console-Guide.md" -> "admin-console-guide"; the wiki's Home is the index (""). */
export function slugFor(file) {
  const name = file.replace(/\.md$/, "");
  return name === "Home" ? "" : name.toLowerCase();
}

function titleOf(file, markdown) {
  const heading = markdown.split("\n").find((line) => line.startsWith("# "));
  return heading ? heading.slice(2).trim() : file.replace(/\.md$/, "").replace(/-/g, " ");
}

/** The wiki sidebar's groups, each a title and the pages under it. */
function navFrom(sidebar, known) {
  const groups = [];
  for (const raw of sidebar.split("\n")) {
    const line = raw.trim();
    const group = line.match(/^\*\*(.+)\*\*$/);
    if (group) {
      groups.push({ title: group[1], pages: [] });
      continue;
    }
    const item = line.match(/^- \[[^\]]+\]\(([A-Za-z0-9-]+)\)$/);
    if (item && groups.length && known.has(`${item[1]}.md`)) groups[groups.length - 1].pages.push(slugFor(`${item[1]}.md`));
  }
  return groups.filter((g) => g.pages.length);
}

export function build() {
  const files = readdirSync(wikiDir)
    .filter((name) => name.endsWith(".md") && !name.startsWith("_"))
    .sort((a, b) => a.localeCompare(b, "en"));
  const pages = files.map((file) => {
    const markdown = readFileSync(join(wikiDir, file), "utf8").replace(/\r\n/g, "\n");
    return { slug: slugFor(file), file, title: titleOf(file, markdown), markdown };
  });
  const nav = navFrom(readFileSync(join(wikiDir, "_Sidebar.md"), "utf8").replace(/\r\n/g, "\n"), new Set(files));
  return (
    "// Generated by tools/build-docs.mjs from wiki/. Do not edit this file:\n" +
    "// edit the wiki page, then run `pnpm run docs` in cloudflare-control.\n\n" +
    "export interface DocsPage {\n  /** The page's address under /docs; empty for the index. */\n  slug: string;\n  /** Its file in wiki/. */\n  file: string;\n  title: string;\n  markdown: string;\n}\n\n" +
    "export interface DocsNavGroup {\n  title: string;\n  /** Slugs, in the order the wiki's sidebar lists them. */\n  pages: string[];\n}\n\n" +
    `export const DOCS_PAGES: readonly DocsPage[] = ${JSON.stringify(pages, null, 2)};\n\n` +
    `export const DOCS_NAV: readonly DocsNavGroup[] = ${JSON.stringify(nav, null, 2)};\n`
  );
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const content = build();
  if (process.argv.includes("--check")) {
    let current = "";
    try {
      current = readFileSync(target, "utf8").replace(/\r\n/g, "\n");
    } catch {
      current = "";
    }
    if (current !== content) {
      console.error("src/docs_content.generated.ts is out of date with wiki/. Run `pnpm run docs` in cloudflare-control.");
      process.exit(1);
    }
    console.log("src/docs_content.generated.ts matches wiki/.");
  } else {
    writeFileSync(target, content, "utf8");
    console.log(`Wrote ${target}`);
  }
}
